i=5
print(i)
print(type(i))
f=0.56
print(f)
print(type(f))
c=1j
print(c)
print(type(c))
str1="Test Statement 1"
print(str1)
print(type(str1))
list1=["Test","Statement",2]
print(list1)
print(type(list1))
tuple1=("Test","Statement",3)
print(tuple1)
print(type(tuple1))
Dict1={"Test":1,"Statement":2,4:3}
print(Dict1)
print(type(Dict1))
bool=True
print(bool)
print(type(bool))
set1={"Test","Statement",5}
print(set1)
print(type(set1))
